# Generated by Django 5.1.4 on 2025-01-09 01:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deptapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Depart',
            fields=[
                ('dept_id', models.AutoField(primary_key=True, serialize=False)),
                ('depart_name', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=300)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.BooleanField(default=True)),
            ],
        ),
        migrations.DeleteModel(
            name='Department',
        ),
        migrations.DeleteModel(
            name='Role',
        ),
    ]
